### PR TITLE
[Embedding] Check dims for Q-R complementary strategy.

### PR DESCRIPTION
**Pull request by ZXYFrank**
According to https://arxiv.org/abs/1909.02107, Quotient-Remainder Complementary Partitions is one of complementary partitions.

However, if the divisors are different, uniqueness of indexing vector for different ids may not be guaranteed, leading to potential collisions. For example, if divM=100 and modM=5, then the results for 7 and 12 are both <0,2>.

### CODE REVIEW

**Review by candyzone — APPROVED** [review]

**Comment by candyzone** [comment]
UT failed
EmbeddingVariable UT(https://github.com/DeepRec-AI/DeepRec/blob/main/tensorflow/python/ops/embedding_variable_ops_test.py#L540) tests multihash_variable dims=[[5,6],[3,6]]
@lixy9474 Is it by design?

**Comment by lixy9474** [comment]
The dim of these two variables can be different.  You can check this algorithm below, where m is dim[0] of one variable and |S|/m is dim[0] of the other variable, so their dim[0] can be different:
 
image

**Comment by ZXYFrank** [comment]
Thanks for your reply. I got it :)

Actually, assume divisor is m = dims[0][0], the conflict-free capacity of MultiHashVariable is actually dims[0][0] * dims[1][0]. In other words, the divisor can be considered either dims[0][0] or dim[1][0], which does not influence the performance.

So, if there should be some checking, it is supposed to check the desired CAPACITY with dims[0][0] * dims[1][0].(since we build MultiHash upon the native Variable in TF, which does not support dynamic capacity growth.)  

However, the CAPACITY is not included in the params of get_multihash_variable now. AFAIC, that may lead to illegal access, am I right?

**Comment by ZXYFrank** [comment]
Thanks for your reply. I got it :)

Actually, assume divisor is m = dims[0][0], the conflict-free capacity of MultiHashVariable is actually dims[0][0] * dims[1][0]. In other words, the divisor can be considered either dims[0][0] or dim[1][0], which does not influence the performance.

So, if there should be some checking, it is supposed to check the desired CAPACITY with dims[0][0] * dims[1][0].(since we build MultiHash upon the native Variable in TF, which does not support dynamic capacity growth.)

However, the CAPACITY is not included in the params of get_multihash_variable now. AFAIC, that may lead to illegal access, am I right?

**Comment by lixy9474** [comment]
> Thanks for your reply. I got it :)
> 
> Actually, assume divisor is m = dims[0][0], the conflict-free capacity of MultiHashVariable is actually dims[0][0] * dims[1][0]. In other words, the divisor can be considered either dims[0][0] or dim[1][0], which does not influence the performance.
> 
> So, if there should be some checking, it is supposed to check the desired CAPACITY with dims[0][0] * dims[1][0].(since we build MultiHash upon the native Variable in TF, which does not support dynamic capacity growth.)
> 
> However, the CAPACITY is not included in the params of get_multihash_variable now. AFAIC, that may lead to illegal access, am I right?

Yes. If the user does not check the id, illegal access is possible. If the user's id exceeds the variable's shape, an error will be reported when calling embedding_lookup.

**Comment by candyzone** [comment]
thanks, @ZXYFrank

**Pull request closed without merging**
